
# Location of the GP include files and the GP library
GPINCLUDE	= ../include
GPLIB		= ../lib

# Location of boost library and thead pool library
BOOSTINCLUDE    = ${INFOWEB_ROOT}/code/libs-ext/include
BOOSTLIB        = ${INFOWEB_ROOT}/code/libs-ext/lib
THREADPOOLINCLUDE = ../threadpool-0_2_5-src/threadpool

# Name of GP library.  Change '.a' to '.so' if you want to use dynamic
# libraries, and change the archive command in src/Makefile as well.
GPLIBFILE = $(GPLIB)/libgp.a

# Compiler flags.  Use -O to optimise
OVERALLCPPFLAGS	= -g -Ofast -march=native -mtune=native -I$(THREADPOOLINCLUDE) -I$(BOOSTINCLUDE)

# Linker flags.
OVERALLLDFLAGS	= -static -L$(BOOSTLIB) -lboost_system -lboost_thread -lpthread

# C++ compiler
#CCC		= CC
CCC		= g++

# Archive command
AR		= ar

# Ranlib command
RANLIB		= ranlib

# Install command and installation directory
INSTALL		= install
INSTALLDIR	= /usr/local
